version: "3.8"

services:
  #============================
  # AUTH SERVICE
  #============================
  # contenedor de la db
  db_auth:
    image: postgres:15
    container_name: smartlogix_postgres_auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data

  # contenedor del microservicio fastapi AUTH
  api_auth:
    build:
      context: ./microservicios/auth_service
    container_name: smartlogix_api_auth
    restart: always
    ports:
      - "8000:8000"
    # leer variables JWT_SECRET_KEY y JWT_ALGORITHM del archivo .env
    env_file:
      - ./microservicios/auth_service/.env
    depends_on:
      - db_auth

  #============================
  # INVENTARIO SERVICE
  #============================
  db_inventario:
    image: postgres:15
    container_name: smartlogix_postgres_inv
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_inventario
    ports:
      - "5433:5432" #5433 para que no choque con la db de Auth
    volumes:
      - postgres_data_inv:/var/lib/postgresql/data

  api_inventario:
    build:
      context: ./microservicios/inventario_service
    container_name: smartlogix_api_inventario
    restart: always
    ports:
      - "8001:8000" #8001 para que no choque con el puerto
    depends_on:
      - db_inventario

volumes:
  postgres_data_auth:
  postgres_data_inv:
