version: "3.8"

services:
  #============================
  # AUTH SERVICE
  #============================
  # contenedor de la db
  db_auth:
    image: postgres:15
    container_name: smartlogix_postgres_auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data

  # contenedor del microservicio fastapi AUTH
  api_auth:
    build:
      context: ./microservicios/auth_service
    container_name: smartlogix_api_auth
    restart: always
    ports:
      - "8000:8000"
    # leer variables JWT_SECRET_KEY y JWT_ALGORITHM del archivo .env
    env_file:
      - ./microservicios/auth_service/.env
    depends_on:
      - db_auth

  #============================
  # INVENTARIO SERVICE
  #============================
  db_inventario:
    image: postgres:15
    container_name: smartlogix_postgres_inv
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_inventario
    ports:
      - "5433:5432" #5433 para que no choque con la db de Auth
    volumes:
      - postgres_data_inv:/var/lib/postgresql/data

  api_inventario:
    build:
      context: ./microservicios/inventario_service
    container_name: smartlogix_api_inventario
    restart: always
    ports:
      - "8001:8000" #8001 para que no choque con el puerto
    depends_on:
      - db_inventario

  #============================
  # PEDIDOS SERVICE
  #============================
  db_pedidos:
    image: postgres:15
    container_name: smartlogix_postgres_pedidos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_pedidos
    ports:
      - "5434:5432" #5434 para que no choque con auth ni inventario
    volumes:
      - postgres_data_pedidos:/var/lib/postgresql/data

  api_pedidos:
    build:
      context: ./microservicios/pedidos_service
    container_name: smartlogix_api_pedidos
    restart: always
    ports:
      - "8002:8000" #8002 para que no choque con auth ni inventario
    environment:
      INVENTARIO_SERVICE_URL: http://api_inventario:8000
    depends_on:
      - db_pedidos
      - api_inventario

  #============================
  # ENVIOS SERVICE
  #============================
  db_envios:
    image: postgres:15
    container_name: smartlogix_postgres_envios
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_envios
    ports:
      - "5435:5432" #5435 para que no choque con auth, inventario ni pedidos
    volumes:
      - postgres_data_envios:/var/lib/postgresql/data

  api_envios:
    build:
      context: ./microservicios/envios_service
    container_name: smartlogix_api_envios
    restart: always
    ports:
      - "8003:8000" #8003 para que no choque con auth, inventario ni pedidos
    depends_on:
      - db_envios

  #============================
  # API GATEWAY
  #============================
  gateway:
    build:
      context: ./api_gateway
    container_name: smartlogix_api_gateway
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./microservicios/auth_service/.env
    depends_on:
      - api_auth
      - api_inventario
      - api_pedidos
      - api_envios

volumes:
  postgres_data_auth:
  postgres_data_inv:
  postgres_data_pedidos:
  postgres_data_envios:
