[pytest]
testpaths =
    microservicios/auth_service/tests
    microservicios/envios_service/tests
    microservicios/inventario_service/tests
    microservicios/pedidos_service/tests
    api_gateway/tests
python_files = test_*.py
asyncio_mode = auto
